language: node_js

node_js:
  - node
  - lts/erbium
  - lts/dubnium

services:
  - mongodb

branches:
  only:
    - master
    - dev

env:
  global:
    - NODE_ENV=test
    - APP_NAME='Express API ES6 Starter'
    - APP_VERSION='1.0.0'
    - TEST_APP_PORT='9945'
    - MONGO_URI=mongodb://localhost:27017/mydb_test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - cp .env.example .env
  - mongo mydb_test &
  - yarn seed:database

script:
  - yarn test
  - yarn test:back:coverage

after_script:
  - yarn codecov
